-- Estrutura do banco: líderes (com login) e contatos vinculados a cada líder
-- Rode este script inteiro no Supabase: Project > SQL Editor > New query > Run
-- Pode ser rodado mais de uma vez sem problema (idempotente).

create table if not exists lider (
    id    bigint generated by default as identity primary key,
    nome  varchar(150) not null
);

create table if not exists contato (
    id             bigint generated by default as identity primary key,
    lider_id       bigint not null references lider(id) on delete cascade,
    nome           varchar(150) not null,
    endereco       varchar(255) not null,
    endereco_lat   double precision,
    endereco_lng   double precision,
    bairro         varchar(100) not null,
    whatsapp       varchar(20)  not null,
    local_votacao  varchar(150) not null,
    liguei         boolean default false,
    observacao     varchar(500),
    data_cadastro  timestamptz default now()
);

alter table contato add column if not exists endereco_lat double precision;
alter table contato add column if not exists endereco_lng double precision;

-- Login e permissões: líder se cadastra sozinho (status "pendente") e só ganha
-- acesso quando um admin aprova (status "aprovado"). Quem tem role "admin" enxerga
-- e gerencia tudo; quem tem role "lider" só enxerga os próprios contatos.
alter table lider add column if not exists email varchar(180);
alter table lider add column if not exists senha_hash varchar(255);
alter table lider add column if not exists role varchar(20) not null default 'lider';
alter table lider add column if not exists status varchar(20) not null default 'pendente';
alter table lider add column if not exists criado_em timestamptz default now();

-- Nome não precisa mais ser único (quem identifica um líder de verdade é o e-mail).
alter table lider drop constraint if exists lider_nome_key;
create unique index if not exists lider_email_key on lider (email) where email is not null;

-- Cache de geocodificação (bairro/escola -> lat/lng) usado no mapa de logística de transporte
-- e nas sugestões de autocompletar do formulário (tipo = 'bairro' ou 'votacao').
create table if not exists local_geo (
    id        bigint generated by default as identity primary key,
    nome      varchar(200) not null unique,
    lat       double precision not null,
    lng       double precision not null,
    tipo      varchar(20),
    criado_em timestamptz default now()
);

create index if not exists idx_contato_lider    on contato(lider_id);
create index if not exists idx_contato_bairro   on contato(bairro);
create index if not exists idx_contato_votacao  on contato(local_votacao);

-- Agenda de compromissos: líder cadastra e só vê os próprios; quem tem role
-- "agenda" ou "admin" vê e gerencia todos os compromissos de todo mundo.
create table if not exists agendamento (
    id            bigint generated by default as identity primary key,
    lider_id      bigint not null references lider(id) on delete cascade,
    nome          varchar(150) not null,
    whatsapp      varchar(20) not null,
    data_hora     timestamptz,
    local         varchar(255) not null,
    observacao    varchar(500),
    criado_em     timestamptz default now()
);

-- Cadastro livre: nenhum campo é obrigatório para salvar um compromisso.
alter table agendamento alter column data_hora drop not null;

create index if not exists idx_agendamento_lider on agendamento(lider_id);
create index if not exists idx_agendamento_data  on agendamento(data_hora);

-- RLS: o backend conecta direto como usuário do Postgres (não via anon key do
-- Supabase), então quem realmente controla acesso é a API (JWT + papel), não o RLS.
-- Deixamos habilitado com policy permissiva por padrão/segurança em profundidade.
alter table lider   enable row level security;
alter table contato enable row level security;

drop policy if exists "lider_all"   on lider;
drop policy if exists "contato_all" on contato;

create policy "lider_all"   on lider   for all using (true) with check (true);
create policy "contato_all" on contato for all using (true) with check (true);

-- Views auxiliares, usadas pelos relatórios em Python
create or replace view vw_contagem_bairro as
select bairro, count(*) as total
from contato
group by bairro
order by total desc;

create or replace view vw_contagem_votacao as
select local_votacao, count(*) as total
from contato
group by local_votacao
order by total desc;
